import { Inter, Lancelot } from "next/font/google";
import "./globals.css";
import Navbar from "./components/Navbar";
import LandingPage from "./components/LandingPage";

const inter = Inter({ subsets: ["latin"] });
import Head from 'next/head';
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <>
      <Head>
        <meta httpEquiv="refresh" content="0; URL=https://tif-task-2-phi.vercel.app/" />
        <title>Redirecting...</title>
      </Head>
      {children}
    </>

  );
}
